#apiVersion: v1
#kind: Secret
#metadata:
#    name: mssql-secret
#type: Opaque
#data:
#    mssql-password: UEBzc3cwcmQK
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-express
  labels:
    app: mssql-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mssql-express
  template:
    metadata:
      labels:
        app: mssql-express
    spec:
      volumes:
      - name: nfsvolume
        hostPath:
          path: /mnt/nfs
      containers:
      - name: mssql-express
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        volumeMounts:
          - name: nfsvolume
            mountPath: "/var/opt/mssql/data"
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "P@ssw0rd"
        - name: ACCEPT_EULA
          value: 'Y'
        - name: MSSQL_PID
          value: Express 
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-express-service
spec:
  selector:
    app: mssql-express
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
