apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pvol
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.33.180
    path: "/mnt/ProdNas/nfs"